xld-service:
  image: ffung/xldeploy:5.5.5
  labels:
    io.rancher.container.pull_image: always
lb:
  image: rancher/load-balancer-service
  ports:
  - ${XLDPORT}:4516
  image: rancher/load-balancer-service
  links:
  - xld-service:xld-service

