jenkins-service:
  image: jenkins:2.19.1-alpine
  labels:
    io.rancher.container.pull_image: always
lb:
  image: rancher/load-balancer-service
  ports:
  - ${JENKINSPORT}:8080
  image: rancher/load-balancer-service
  links:
  - jenkins-service:jenkins-service
