xlr-service:
  image: rchrd/xlrelease:5.0.1
  labels:
    io.rancher.container.pull_image: always
lb:
  image: rancher/load-balancer-service
  ports:
  - ${XLRPORT}:5516
  image: rancher/load-balancer-service
  links:
  - xlr-service:xlr-service
