xld-service:
  image: ffung/xldeploy
xlr-service:
  image: rchrd/xlrelease:5.0.1
jenkins-service:
  image: jenkins
lb:
  image: rancher/load-balancer-service
  ports:
  - ${XLDPORT}:4516
  - ${XLRPORT}:5516
  - ${JENKINSPORT}:8080
  image: rancher/load-balancer-service
  links:
  - xld-service:xld-service
  - xlr-service:xlr-service
  - jenkins-service:jenkins-service
